INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Roque Sosa', 10);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Eduardo Paveto', 20);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Nicolas Garcia', 30);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Chester Roscoe', 10);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Russel Mccall', 102);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Erick Adams', 87);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Harvey Wellington', 93);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Benny Herbert', 22);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Brad Morrison', 82);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Carter Murray', 119);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Josh Vangness', 95);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Roger Crawford', 7);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('William Uttley', 112);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Marvin Knight', 38);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Luke Richards', 111);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Javier Warner', 119);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Chad Nayler', 64);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Tyler Shaw', 70);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Tyler Owen', 39);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Chris Allcott', 86);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Martin Hill', 8);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Hank Michael', 57);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Ron Ainsworth', 57);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('David Logan', 83);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Sebastian Lee', 97);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Mason Abbot', 39);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Bob Sinclair', 8);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Domenic Collingwood', 111);

INSERT INTO PROJECT (NAME)
VALUES ('Plan EOY Party');
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE, PROJECT)
VALUES (1, 1);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE, PROJECT)
VALUES (3, 1);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE, PROJECT)
VALUES (2, 1);
INSERT INTO TASK (NAME, DESCRIPTION, ESTIMATED_HOURS, CREATED_DATE, ACTUAL_DURATION,
                  PROJECT, ASSIGNED_EMPLOYEE)
VALUES ('Book Venue',
        'Find and send deposit for a venue to host the event',
        3,
        {ts '2022-07-06 18:47:52'},
        1,
        1,
        20);
INSERT INTO TASK (NAME, DESCRIPTION, ESTIMATED_HOURS, CREATED_DATE, ACTUAL_DURATION,
                  PROJECT, ASSIGNED_EMPLOYEE)
VALUES ('Find Catering',
        'Find and send deposit for a catering company to serve in the event',
        3,
        {ts '2022-07-06 18:48:52'},
        1,
        1,
        20);
INSERT INTO TASK (NAME, DESCRIPTION, ESTIMATED_HOURS, CREATED_DATE, ACTUAL_DURATION,
                  PROJECT, ASSIGNED_EMPLOYEE)
VALUES ('Send Invites',
        'Send invites to employess with all the details of the event',
        2,
        {ts '2022-07-06 18:49:52'},
        3,
        1,
        20);

INSERT INTO PROJECT (NAME)
VALUES ('Create Q2 Report');
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE, PROJECT)
VALUES (1, 2);

INSERT INTO PROJECT (NAME)
VALUES ('Inventory System Application');
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE, PROJECT)
VALUES (1, 3);
INSERT INTO EMPLOYEE_PROJECT (EMPLOYEE, PROJECT)
VALUES (2, 3);
