INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Roque Sosa', 10);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Eduardo Paveto', 20);
INSERT INTO EMPLOYEE (NAME, COST_PER_HOUR)
VALUES ('Nicolas Garcia', 30);
