CREATE TABLE EMPLOYEE
(
    ID            IDENTITY PRIMARY KEY,
    NAME          TEXT,
    COST_PER_HOUR INTEGER
);

CREATE TABLE PROJECT
(
    ID   IDENTITY PRIMARY KEY,
    NAME TEXT
);

CREATE TABLE EMPLOYEE_PROJECT
(
    EMPLOYEE INTEGER,
    PROJECT  INTEGER,
    PRIMARY KEY (EMPLOYEE, PROJECT)
);

CREATE TABLE TASK
(
    ID                IDENTITY PRIMARY KEY,
    NAME              TEXT,
    DESCRIPTION       TEXT,
    ESTIMATED_HOURS   INTEGER,
    CREATED_DATE      TIMESTAMP,
    ACTUAL_DURATION   INTEGER,
    STATUS            TEXT,
    PROJECT           INTEGER,
    ASSIGNED_EMPLOYEE INTEGER
);

CREATE TABLE COMMENT
(
    ID      IDENTITY PRIMARY KEY,
    CONTENT TEXT,
    TASK    INTEGER
);
